"""
Lua配置生成服务
"""
from typing import List
from ..models.schemas import GunConfig, RecoilData, SensitivitySettings


class LuaGenerator:
    """Lua配置生成器"""
    
    # Lua脚本模板
    SCRIPT_TEMPLATE = '''--FPS压枪宏 v2.0 - Generated by Recoil Studio
--支持多枪械配置、按子弹弹道配置、固定/多段射速计算、灵敏度修正、倍镜适配

--====================================================================================
-- 基础配置
--====================================================================================
local scriptName = "RecoilStudio_SCRIPT"
local showLog = true                    -- 是否打印日志
local clickBtn = 1                      -- 触发按键 (左键=1)
local smoothSteps = 8                   -- 平滑压枪段数：每发子弹拆成多次小移动，越大越柔和
local smoothPollInterval = 4            -- 平滑等待检查间隔：用于尽快识别松开左键
local retriggerWindow = 300             -- 左键重捕窗口：松开后短时间内重新按下，不依赖新的左键事件

-- 按键配置
local toggleBtn = 2                     -- 压枪开关 (右键=2)
local gunSwitchUpBtn = 8                -- 切换下一把枪 (DPI+)
local gunSwitchDnBtn = 7                -- 切换上一把枪 (DPI-)
local resetPointBtn = 5                 -- 鼠标复位开关 (前进键)
local resetConfigBtn = 9                -- 配置复位 (G9键)

--====================================================================================
-- 灵敏度配置（根据游戏内设置填写）
--====================================================================================
local mouseSens = %MOUSE_SENS%                     -- 鼠标灵敏度
local verticalSens = %VERTICAL_SENS%               -- 垂直灵敏度
local horizontalSens = %HORIZONTAL_SENS%           -- 水平灵敏度
local adsSensMul = %ADS_SENS_MUL%                  -- 举枪灵敏度加成
local adsVerticalSens = %ADS_VERTICAL_SENS%        -- 举枪瞄准垂直灵敏度
local adsHorizontalSens = %ADS_HORIZONTAL_SENS%    -- 举枪瞄准水平灵敏度
local screenDistCoeff = %SCREEN_DIST_COEFF%        -- 屏幕距离系数
local baseFOV = %BASE_FOV%                         -- 基础视场角(度)
local holdBreath = %HOLD_BREATH%                    -- 是否屏息
local baseSens = 5                                 -- 弹道数据标定时的鼠标灵敏度，默认按项目基准5计算

--====================================================================================
-- 枪械配置
--====================================================================================
local guns = {
%GUNS_CONFIG%
}

--====================================================================================
-- 运行时状态
--====================================================================================
local currentGunIndex = 1
local currentBullet = 0
local recoilEnabled = false
local resetPointState = false
local totalMoveY = 0
local totalMoveX = 0
local errorY = 0
local errorX = 0

--====================================================================================
-- 辅助函数
--====================================================================================

-- 保护灵敏度除法，避免手动改配置时出现0或负数导致补偿失效
function safeSens(value)
    if value == nil or value <= 0 then
        return 1
    end
    return value
end

-- 计算指定FOV半角在MDV屏幕距离上的视角；MDV标准写法是 atan(coeff * tan(fov/2))
function calcMonitorDistanceAngle(halfFovRad, coeff)
    if coeff <= 0 then
        -- MDV为0时匹配准星中心，使用极限值避免 atan(0)/atan(0)
        return math.tan(halfFovRad)
    end
    return math.atan(math.tan(halfFovRad) * coeff)
end

-- 计算倍镜灵敏度比 (scoped_sens / base_sens)
-- 基于MDV/FOV换算：先由倍率得到开镜FOV，再按屏幕距离系数计算灵敏度比例
function calcScopeSensRatio(zoom)
    if zoom <= 1 then return 1 end
    local rad = math.pi / 180
    local halfBaseRad = baseFOV / 2 * rad
    local halfScopedRad = math.atan(math.tan(halfBaseRad) / zoom)
    local baseAngle = calcMonitorDistanceAngle(halfBaseRad, screenDistCoeff)
    local scopedAngle = calcMonitorDistanceAngle(halfScopedRad, screenDistCoeff)
    if baseAngle == 0 then return 1 end
    return scopedAngle / baseAngle
end

function getCurrentGun()
    return guns[currentGunIndex]
end

function safeRpm(rpm)
    if rpm == nil or rpm <= 0 then
        return 600
    end
    return rpm
end

function getBulletRpm(bulletIndex)
    local gun = getCurrentGun()

    if gun.rpmSegments ~= nil and #gun.rpmSegments > 0 then
        -- 多段射速按截止发数升序匹配；最后一段没有endBullet时覆盖后续所有子弹
        for i = 1, #gun.rpmSegments do
            local segment = gun.rpmSegments[i]
            if segment.endBullet == nil or bulletIndex <= segment.endBullet then
                return safeRpm(segment.rpm)
            end
        end
    end

    return safeRpm(gun.rpm)
end

function getSleepTime(bulletIndex)
    return math.floor(60000 / getBulletRpm(bulletIndex))
end

function getGunRpmLabel(gun)
    if gun.rpmSegments == nil or #gun.rpmSegments == 0 then
        return tostring(safeRpm(gun.rpm))
    end

    local labels = {}
    for i = 1, #gun.rpmSegments do
        local segment = gun.rpmSegments[i]
        local rangeLabel = segment.endBullet == nil and "after" or tostring(segment.endBullet)
        labels[#labels + 1] = string.format("%s:%d", rangeLabel, safeRpm(segment.rpm))
    end
    return table.concat(labels, "/")
end

function getBulletRecoil(bulletIndex)
    local gun = getCurrentGun()
    local pattern = gun.pattern

    if bulletIndex > #pattern then
        bulletIndex = #pattern
    end
    if bulletIndex < 1 then
        bulletIndex = 1
    end

    local recoil = pattern[bulletIndex]

    -- 灵敏度修正计算：游戏灵敏度越高，同样角度需要的鼠标移动量越少，所以补偿量按灵敏度倒数缩放
    local sensRatio = baseSens / safeSens(mouseSens)
    local verticalSensFactor = 1 / safeSens(verticalSens)
    local horizontalSensFactor = 1 / safeSens(horizontalSens)
    local adsSensFactor = 1 / safeSens(adsSensMul)

    -- 倍镜修正：灵敏度比<1说明开镜后灵敏度降低，补偿量需要除以该比值
    local scopeSensRatio = calcScopeSensRatio(gun.scopeZoom)
    local scopeFactor = 1 / scopeSensRatio
    local adsVertFactor = adsSensFactor * (1 / safeSens(adsVerticalSens)) * scopeFactor
    local adsHorizFactor = adsSensFactor * (1 / safeSens(adsHorizontalSens)) * scopeFactor

    -- 屏息修正
    local breathFactor = 1
    if holdBreath then
        breathFactor = gun.holdBreathCoeff
    end

    local moveY = recoil.y * gun.verticalMul * sensRatio * verticalSensFactor * adsVertFactor * breathFactor
    local moveX = recoil.x * gun.horizontalMul * sensRatio * horizontalSensFactor * adsHorizFactor * breathFactor

    return moveY, moveX
end

function applyMovement(rawY, rawX)
    local totalY = rawY + errorY
    local totalX = rawX + errorX
    
    local moveY = totalY >= 0 and math.floor(totalY) or math.ceil(totalY)
    local moveX = totalX >= 0 and math.floor(totalX) or math.ceil(totalX)
    
    errorY = totalY - moveY
    errorX = totalX - moveX
    
    return moveY, moveX
end

function waitUntilPressed(targetTime)
    -- 按真实运行时间等待，避免多次 Sleep(1) 累计误差导致压枪速度变慢
    while IsMouseButtonPressed(clickBtn) do
        local remainTime = targetTime - GetRunningTime()
        if remainTime <= 0 then
            return true
        end

        if remainTime > smoothPollInterval then
            Sleep(smoothPollInterval)
        else
            Sleep(remainTime)
        end
    end

    return false
end

function sleepWhilePressed(ms)
    if ms <= 0 then
        return IsMouseButtonPressed(clickBtn)
    end

    -- 使用目标时间等待，保证等待时长接近原始射速节奏
    return waitUntilPressed(GetRunningTime() + math.floor(ms))
end

function waitForReTrigger(ms)
    local endTime = GetRunningTime() + math.floor(ms)

    -- 左键松开后短时间主动捕捉下一次按下，避免 OnEvent 忙碌时丢失快速二次触发
    while GetRunningTime() < endTime do
        if IsMouseButtonPressed(clickBtn) then
            return true
        end
        Sleep(smoothPollInterval)
    end

    return false
end

function switchGun(delta)
    currentGunIndex = currentGunIndex + delta
    if currentGunIndex < 1 then
        currentGunIndex = #guns
    end
    if currentGunIndex > #guns then
        currentGunIndex = 1
    end
    local gun = getCurrentGun()
    log("Switch to gun: %s (RPM=%s)", gun.name, getGunRpmLabel(gun))
end

function log(str, ...)
    if showLog then
        OutputLogMessage(scriptName .. "-[INFO]-" .. str .. "\\n", ...)
    end
end

--====================================================================================
-- 核心功能
--====================================================================================

EnablePrimaryMouseButtonEvents(true)

function OnEvent(event, arg)
    log("event=%s,arg=%s", event, arg)
    
    if event == "MOUSE_BUTTON_PRESSED" and arg == toggleBtn then
        recoilEnabled = not recoilEnabled
        log("Recoil control: %s", recoilEnabled and "ON" or "OFF")
        return
    end
    
    if event == "MOUSE_BUTTON_PRESSED" and arg == gunSwitchUpBtn then
        switchGun(1)
        return
    end
    
    if event == "MOUSE_BUTTON_PRESSED" and arg == gunSwitchDnBtn then
        switchGun(-1)
        return
    end
    
    if event == "MOUSE_BUTTON_PRESSED" and arg == resetPointBtn then
        resetPointState = not resetPointState
        log("Mouse reset: %s", resetPointState and "ON" or "OFF")
        return
    end
    
    if event == "MOUSE_BUTTON_PRESSED" and arg == resetConfigBtn then
        resetConfig()
        return
    end
    
    if event == "MOUSE_BUTTON_PRESSED" and arg == clickBtn and recoilEnabled then
        beginRecoilControl()
    end
end

function beginRecoilControl()
    local gun = getCurrentGun()
    
    -- 模拟人类反应延迟，避免按下瞬间立即补偿被检测
    Sleep(math.random(20, 50))
    
    -- 随机缓动指数，控制子步位移分配节奏，避免匀速分帧被检测
    local easeK = 0.90 + math.random() * 0.20
    local easeSteps = smoothSteps
    if easeSteps < 1 then easeSteps = 1 end
    local easeWeights = {}
    local invSteps = 1.0 / easeSteps
    for i = 1, easeSteps do
        easeWeights[i] = (i * invSteps) ^ easeK - ((i - 1) * invSteps) ^ easeK
    end
    
    totalMoveY = 0
    totalMoveX = 0
    
    log("Start recoil control: %s, RPM=%s", gun.name, getGunRpmLabel(gun))

    repeat
        currentBullet = 0
        errorY = 0
        errorX = 0
        local keepShooting = true

        repeat
            currentBullet = currentBullet + 1

            local sleepTime = getSleepTime(currentBullet)
            local rawY, rawX = getBulletRecoil(currentBullet)
            local bulletMoveY = 0
            local bulletMoveX = 0
            local bulletStartTime = GetRunningTime()
            for i = 1, easeSteps do
                if not IsMouseButtonPressed(clickBtn) then
                    keepShooting = false
                    break
                end

                -- 每一小段继续使用误差累计，保证平滑后总位移仍尽量贴近原始弹道
                local moveY, moveX = applyMovement(rawY * easeWeights[i], rawX * easeWeights[i])

                bulletMoveY = bulletMoveY + moveY
                bulletMoveX = bulletMoveX + moveX
                totalMoveY = totalMoveY + moveY
                totalMoveX = totalMoveX + moveX

                if moveY ~= 0 or moveX ~= 0 then
                    MoveMouseRelative(moveX, moveY)
                end

                if i < easeSteps then
                    -- 每段按固定时间点执行，既保持平滑，也避免 Sleep 误差拖慢整体射速
                    local stepTime = bulletStartTime + math.floor(sleepTime * i / easeSteps)
                    if not waitUntilPressed(stepTime) then
                        keepShooting = false
                        break
                    end
                end
            end

            if not keepShooting then
                break
            end

            log("Bullet #%d: smoothMove=(%d,%d)", currentBullet, bulletMoveY, bulletMoveX)

            -- 等到下一发理论时间点，保持原有 RPM 射速节奏不变
            if not waitUntilPressed(bulletStartTime + sleepTime) then
                keepShooting = false
                break
            end

        until currentBullet >= #gun.pattern or not keepShooting

        log("Stop at bullet #%d", currentBullet)

    until not waitForReTrigger(retriggerWindow)
    
    if resetPointState and (totalMoveY ~= 0 or totalMoveX ~= 0) then
        resetMousePosition()
    end
end

function resetMousePosition()
    log("Resetting mouse position...")
    
    local steps = 20
    local stepY = math.floor(-totalMoveY / steps)
    local stepX = math.floor(-totalMoveX / steps)
    
    for i = 1, steps do
        MoveMouseRelative(stepX, stepY)
        Sleep(4)
    end
    
    local remainY = -totalMoveY - (stepY * steps)
    local remainX = -totalMoveX - (stepX * steps)
    if remainY ~= 0 or remainX ~= 0 then
        MoveMouseRelative(remainX, remainY)
    end
end

function resetConfig()
    log("Config reset")
    currentGunIndex = 1
    recoilEnabled = false
    resetPointState = false
    log("Current gun: %s", getCurrentGun().name)
end
'''
    
    @classmethod
    def generate(cls, guns: List[GunConfig], sensitivity: SensitivitySettings = None) -> str:
        """生成完整的Lua脚本"""
        if sensitivity is None:
            sensitivity = SensitivitySettings()
        guns_config = cls._generate_guns_config(guns)
        script = cls.SCRIPT_TEMPLATE.replace("%GUNS_CONFIG%", guns_config)
        script = script.replace("%MOUSE_SENS%", str(sensitivity.mouse_sens))
        script = script.replace("%VERTICAL_SENS%", str(sensitivity.vertical_sens))
        script = script.replace("%HORIZONTAL_SENS%", str(sensitivity.horizontal_sens))
        script = script.replace("%ADS_SENS_MUL%", str(sensitivity.ads_sens_mul))
        script = script.replace("%ADS_VERTICAL_SENS%", str(sensitivity.ads_vertical_sens))
        script = script.replace("%ADS_HORIZONTAL_SENS%", str(sensitivity.ads_horizontal_sens))
        script = script.replace("%SCREEN_DIST_COEFF%", str(sensitivity.screen_dist_coeff))
        script = script.replace("%BASE_FOV%", str(sensitivity.base_fov))
        script = script.replace("%HOLD_BREATH%", "true" if sensitivity.hold_breath else "false")
        return script
    
    @classmethod
    def _generate_guns_config(cls, guns: List[GunConfig]) -> str:
        """生成枪械配置部分"""
        configs = []
        
        for gun in guns:
            config = cls._generate_single_gun(gun)
            configs.append(config)
        
        return "\n".join(configs)
    
    @classmethod
    def _generate_single_gun(cls, gun: GunConfig) -> str:
        """生成单把枪械的配置"""
        lines = []
        lines.append(f"    -- {gun.name}")
        lines.append("    {")
        lines.append(f'        name = "{gun.name}",')
        lines.append(f'        rpm = {gun.rpm},')
        rpm_segments = cls._normalize_rpm_segments(gun)
        if rpm_segments:
            lines.append('        -- 多段射速：没有endBullet的最后一段表示后续所有子弹')
            lines.append('        rpmSegments = {')
            for segment in rpm_segments:
                end_part = "" if segment.end_bullet is None else f'endBullet={segment.end_bullet}, '
                lines.append(f'            {{{end_part}rpm={segment.rpm}}},')
            lines.append('        },')
        lines.append(f'        verticalMul = {gun.vertical_mul},')
        lines.append(f'        horizontalMul = {gun.horizontal_mul},')
        lines.append(f'        scopeZoom = {gun.scope_zoom},')
        lines.append(f'        holdBreathCoeff = {gun.hold_breath_coeff},')
        lines.append('        pattern = {')
        
        for i, p in enumerate(gun.pattern):
            y_val = round(p.y, 6)
            x_val = round(p.x, 6)
            lines.append(f'            {{y={y_val}, x={x_val}}},    -- 第{i+1}发')
        
        lines.append('        }')
        lines.append('    },')
        
        return "\n".join(lines)

    @classmethod
    def _normalize_rpm_segments(cls, gun: GunConfig):
        """清洗多段射速，保证Lua只收到递增且有效的分段"""
        if not gun.rpm_segments:
            return []

        segments = []
        previous_end = 0
        for index, segment in enumerate(gun.rpm_segments):
            if segment.rpm <= 0:
                continue

            # 最后一段允许不写截止发数，代表后续所有子弹都使用该射速
            if segment.end_bullet is None:
                segments.append(segment)
                break

            if segment.end_bullet <= previous_end:
                continue

            segments.append(segment)
            previous_end = segment.end_bullet

            if index == len(gun.rpm_segments) - 1:
                break

        return segments
